# Generated by Django 4.0.3 on 2022-11-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Peoples',
        ),
    ]
