# Generated by Django 4.0.3 on 2022-11-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_rename_users_peoples'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peoples',
            name='email',
        ),
    ]
